# This is a basic workflow to help you get started with Actions

name: Build APK

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#   test:
#     name: Run Unit Tests
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2.3.4
#       - name: Setup up JDK 1.8
#         uses: actions/setup-java@v1.4.3
#         with:
#           java-version: 1.8
#       - name: Unit tests
#         run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.1
        with:
          name: app-1.0.${{github.run_number}}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 1
  notification:
    name: Notification to Slack
    needs: [apk]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: app-1.0.${{github.run_number}}
          path: artifact/download/debug
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifact/download/debug
      - name: Upload to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          path: artifact/download/debug/app-debug.apk
          channel: dev-app-station
          initial_comment: Versi 3.3.${{github.run_number}}
          title: app-debug-1.0.${{github.run_number}}.apk
          filename: app-debug-1.0.${{github.run_number}}.apk
